#!/bin/bash

set -o nounset -o pipefail -o errexit

if [ -f "./.env" ]; then
    set -a
    . "./.env"
    set +a
fi

SCRIPT_DIR=$(readlink -f $0 | xargs dirname)
ROOT=${ROOT-$SCRIPT_DIR/..}
BIN=${BIN-$ROOT/bin}

"$BIN/whereami" current --json --output="$ROOT/.build.json"

DOCKER_IMAGE=${DOCKER_IMAGE-$1}
SUDO=${SUDO-}

TMP=$(mktemp -d)
trap 'rm -rf $TMP' EXIT

ARGS=()
ARGS+=("--progress=plain")
ARGS+=("--iidfile=$TMP/docker.image")
ARGS+=("--tag=$DOCKER_IMAGE")
ARGS+=(".")

if [ -n "${GITHUB_ACTION-}" ]; then
    # https://github.com/moby/buildkit#github-actions-cache-experimental
    docker buildx build \
        --output=type=docker \
        --cache-to type=gha,mode=max \
        --cache-from type=gha \
        --load \
        "${ARGS[@]}"
else
  $SUDO docker build --push "${ARGS[@]}"
fi

echo 1>&2 "built image: $(<$TMP/docker.image)"
cat "$TMP/docker.image"
