#!/bin/bash

set -o nounset -o pipefail -o errexit

DOCKER_IMAGE=${DOCKER_IMAGE-$1}

HOST=$(sed "s,\(\w\+\)/.*,\1," <<< "$DOCKER_IMAGE")
IFS='.' read -ra PARTS <<< "$HOST"
REGION="${PARTS[3]}"
SUDO=${SUDO-}

ARGS=("--region=$REGION")

if [ -n "${AWS_PROFILE-}" ]; then
    ARGS+=("--profile=$AWS_PROFILE")
fi

aws ecr get-login-password "${ARGS[@]}" \
    | $SUDO docker login --username AWS --password-stdin "$HOST"
