#!/bin/bash

set -o nounset -o pipefail -o errexit

DOCKER_IMAGE=${DOCKER_IMAGE-$1}
DOCKER_IMAGE_ID=${DOCKER_IMAGE_ID-${2-$(cat .docker.image)}}
LAMBDA_ARN=${LAMBDA_ARN-$3}
REGION=$(cut -d':' -f 4 <<< "$LAMBDA_ARN")

IMAGE_URI=$(docker inspect "$DOCKER_IMAGE_ID" --format '{{ index .RepoDigests 0 }}')
echo 1>&2 "setting image uri: $IMAGE_URI"

aws lambda update-function-code \
    --profile="$AWS_PROFILE" \
    --region="$REGION" \
    --function-name="$LAMBDA_ARN" \
    --image-uri="$IMAGE_URI"
