name: Build Docker image
on:
  push:
    branches-ignore: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
        DOCKER_IMAGE: ${{ vars.DOCKER_IMAGE }}
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Build Docker image
      run: .github/docker-build
