name: Build and upload Docker image
on: [ push ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DOCKER_IMAGE: ${{ vars.DOCKER_IMAGE }}
        ROLE_ARN: ${{ vars.ROLE_ARN }}
        LAMBDA_ARN: ${{ vars.LAMBDA_ARN }}
        AWS_PROFILE: ecr
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure AWS CLI profiles
      run: |
        mkdir -p "$HOME/.aws"
        envsubst < .github/aws.config.template > "$HOME/.aws/config"

    - name: Log in to ECR
      run: .github/ecr-login

    - name: Build Docker image
      run: .github/docker-build > docker.image

    - name: Tag and push images
      run: |
          for t in "$DOCKER_IMAGE:$GITHUB_REF_NAME" "$DOCKER_IMAGE:$GITHUB_SHA"; do
              docker tag "$(cat docker.image)" "$t"
              docker push "$t"
          done

    - name: Reconfigure the Lambda function's image
      run: .github/reconfigure-lambda "$(cat docker.image)"
