name: Build and upload Docker image
on: [ push ]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DOCKER_REPO: ${{ vars.DOCKER_REPO }}
        ECR_ROLE_ARN: ${{ vars.ECR_ROLE_ARN }}
        AWS_PROFILE: ecr
        DOCKER_IMAGE_NAME: publisher
    steps:
    - name: Check out repository code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Configure AWS CLI profiles
      run: |
        mkdir -p "$HOME/.aws"
        envsubst < .github/aws.config.template > "$HOME/.aws/config"

    - name: Log in to ECR
      run: .github/ecr-login

    - name: Build Docker image
      run: make docker

    - name: Tag and push images
      run: |
          for t in "$DOCKER_REPO:latest" "$DOCKER_REPO:$GITHUB_SHA"; do
              docker tag "$(cat .docker.image)" "$t"
              docker push "$t"
          done
