name: Build, upload and publish
on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        DOCKER_IMAGE: ${{ vars.DOCKER_IMAGE }}
        ROLE_ARN: ${{ vars.ROLE_ARN }}
        LAMBDA_ARN: ${{ vars.LAMBDA_ARN }}
        LAMBDA_TIMEOUT: 600
        AWS_PROFILE: ecr
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver-opts: image=moby/buildkit:v0.12.2
        buildkitd-flags: --debug

    - name: Expose GitHub Runtime
      uses: crazy-max/ghaction-github-runtime@v3

    - name: Check out repository code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Configure GnuPG
      run: |
        gpgconf --list-components | cut -f1 -d':' | xargs -I{} gpgconf --kill {}
        export GNUPGHOME="$HOME/.gnupg"
        rm -rf "$GNUPGHOME"
        mkdir "$GNUPGHOME"
        chmod 700 "$GNUPGHOME"
        echo "auto-key-retrieve" > "$GNUPGHOME/gpg.conf"
        echo "keyserver hkp://keyserver.ubuntu.com:80" > "$GNUPGHOME/dirmngr.conf"
        echo "GNUPGHOME=$GNUPGHOME" >> "$GITHUB_ENV"

    - name: Configure AWS CLI profiles
      run: |
        mkdir -p "$HOME/.aws"
        envsubst < .github/aws.config.template > "$HOME/.aws/config"

    - name: Log in to ECR
      run: .github/ecr-login

    - name: Build Docker image
      run: .github/docker-build > .docker.image

    - name: Tag and push images
      run: |
          for t in "$DOCKER_IMAGE:$GITHUB_REF_NAME" "$DOCKER_IMAGE:$GITHUB_SHA"; do
              docker tag "$(cat .docker.image)" "$t"
              docker push "$t"
          done

    - name: Reconfigure the Lambda function's image
      run: .github/reconfigure-lambda "$(cat .docker.image)"

    - name: Invoke the Lambda function
      run: .github/invoke-lambda
